In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('./NBA Shot Locations.csv')

In [17]:
df.columns

Index(['Game ID', 'Game Event ID', 'Player ID', 'Player Name', 'Team ID',
       'Team Name', 'Period', 'Minutes Remaining', 'Seconds Remaining',
       'Action Type', 'Shot Type', 'Shot Zone Basic', 'Shot Zone Area',
       'Shot Zone Range', 'Shot Distance', 'X Location', 'Y Location',
       'Shot Made Flag', 'Game Date', 'Home Team', 'Away Team', 'Season Type'],
      dtype='object')

In [18]:
df.shape

(4729512, 22)

In [19]:
df.head()

,Game ID,Game Event ID,Player ID,Player Name,Team ID,Team Name,Period,Minutes Remaining,Seconds Remaining,Action Type,...,Shot Zone Area,Shot Zone Range,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date,Home Team,Away Team,Season Type
0,29700427,389,100,Tim Legler,1610612764,Washington Wizards,4,11,22,Jump Shot,...,Right Side(R),8-16 ft.,15,117,109,1,19980102,WAS,IND,Regular Season
1,29700427,406,100,Tim Legler,1610612764,Washington Wizards,4,9,36,Jump Shot,...,Right Side(R),8-16 ft.,14,143,25,0,19980102,WAS,IND,Regular Season
2,29700427,475,100,Tim Legler,1610612764,Washington Wizards,4,3,7,Jump Shot,...,Left Side(L),8-16 ft.,10,-87,55,0,19980102,WAS,IND,Regular Season
3,29700427,487,100,Tim Legler,1610612764,Washington Wizards,4,1,45,Jump Shot,...,Center(C),Less Than 8 ft.,5,-1,53,0,19980102,WAS,IND,Regular Season
4,29700427,497,100,Tim Legler,1610612764,Washington Wizards,4,0,45,Jump Shot,...,Right Side(R),8-16 ft.,14,89,113,0,19980102,WAS,IND,Regular Season

In [20]:
# Uncomment to sample 1% of dataframe to test operations faster; re-comment for final cleanup of raw data
# df = df.sample(frac=.01).reset_index(drop=True)
# df.shape

### Clean up Team Names
The New Orleans Hornets played in Oklahoma City following hurricane Katria; Recoding these "New Orleans/Oklahoma City Hornets" values as "New Orleans Hornets"

In [21]:
name_replace = {'New Orleans/Oklahoma City Hornets':'New Orleans Hornets'}
df['Team Name'] = df['Team Name'].replace(name_replace)

### Change Game Date to datetime

In [22]:
df['Game Date'] = pd.to_datetime(df['Game Date'], format='%Y%m%d')

In [23]:
df.head(10)

,Game ID,Game Event ID,Player ID,Player Name,Team ID,Team Name,Period,Minutes Remaining,Seconds Remaining,Action Type,...,Shot Zone Area,Shot Zone Range,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date,Home Team,Away Team,Season Type
0,29700427,389,100,Tim Legler,1610612764,Washington Wizards,4,11,22,Jump Shot,...,Right Side(R),8-16 ft.,15,117,109,1,1998-01-02,WAS,IND,Regular Season
1,29700427,406,100,Tim Legler,1610612764,Washington Wizards,4,9,36,Jump Shot,...,Right Side(R),8-16 ft.,14,143,25,0,1998-01-02,WAS,IND,Regular Season
2,29700427,475,100,Tim Legler,1610612764,Washington Wizards,4,3,7,Jump Shot,...,Left Side(L),8-16 ft.,10,-87,55,0,1998-01-02,WAS,IND,Regular Season
3,29700427,487,100,Tim Legler,1610612764,Washington Wizards,4,1,45,Jump Shot,...,Center(C),Less Than 8 ft.,5,-1,53,0,1998-01-02,WAS,IND,Regular Season
4,29700427,497,100,Tim Legler,1610612764,Washington Wizards,4,0,45,Jump Shot,...,Right Side(R),8-16 ft.,14,89,113,0,1998-01-02,WAS,IND,Regular Season
5,29700449,79,100,Tim Legler,1610612764,Washington Wizards,1,2,17,Jump Shot,...,Left Side(L),24+ ft.,23,-231,42,0,1998-01-04,WAS,PHX,Regular Season
6,29700449,152,100,Tim Legler,1610612764,Washington Wizards,2,6,48,Jump Shot,...,Left Side(L),16-24 ft.,17,-166,59,0,1998-01-04,WAS,PHX,Regular Season
7,29700449,336,100,Tim Legler,1610612764,Washington Wizards,3,0,39,Jump Shot,...,Center(C),Less Than 8 ft.,4,23,36,0,1998-01-04,WAS,PHX,Regular Season
8,29700453,141,100,Tim Legler,1610612764,Washington Wizards,2,9,41,Jump Shot,...,Right Side(R),8-16 ft.,12,123,-18,0,1998-01-05,NYK,WAS,Regular Season
9,29700482,116,100,Tim Legler,1610612764,Washington Wizards,2,10,39,Jump Shot,...,Left Side(L),8-16 ft.,13,-130,31,0,1998-01-09,ATL,WAS,Regular Season

### Create Season Column based on Game_ID convention
Game ID convention is 10 digits total as follows:<br><br>
*Two leading zeros, which may be dropped<br>
*One digit prefix for season type (1 = pre-season; 2 = regular season; 4 = post-season)<br>
*Two digit year for season year (97 = 1997-98 season, etc...)<br>
*Five digit suffix based on the order the games were played in the season, xxxxx00100 is the 100th game of the season chronologically

In [24]:
df2 = pd.DataFrame()

In [25]:
df2['Game ID'] = df['Game ID'].astype('str')
df2['Game ID'].head()

0    29700427
1    29700427
2    29700427
3    29700427
4    29700427
Name: Game ID, dtype: object

### Extact two-digit year

In [26]:
df2['Year Two Digit'] = df2['Game ID'].str.slice(1,3).astype('int16')
df2['Year Two Digit']

0          97
1          97
2          97
3          97
4          97
           ..
4729507    18
4729508    18
4729509    18
4729510    18
4729511    18
Name: Year Two Digit, Length: 4729512, dtype: int16

### Define dictionary of mappings for two-digit years to nba seasons

In [32]:
season_dict = {97:'1997-98',
          98:'1998-99',
          99:'1999-00',
          0:'2000-01',
          1:'2001-02',
          2:'2002-03',
          3:'2003-04',
          4:'2004-05',
          5:'2004-06',
          6:'2006-07',
          7:'2007-08',
          8:'2008-09',
          9:'2009-10',
          10:'2010-11',
          11:'2011-12',
          12:'2012-13',
          13:'2013-14',
          14:'2014-15',
          15:'2015-16',
          16:'2016-17',
          17:'2017-18',
          18:'2018-19',
          19:'2019-20'
          }

### Map years to seasons

In [33]:
df2['Season'] = df2['Year Two Digit'].replace(season_dict)
df['Season'] = df2['Season']

In [30]:
df.head()

,Game ID,Game Event ID,Player ID,Player Name,Team ID,Team Name,Period,Minutes Remaining,Seconds Remaining,Action Type,...,Shot Zone Range,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date,Home Team,Away Team,Season Type,Season
0,29700427,389,100,Tim Legler,1610612764,Washington Wizards,4,11,22,Jump Shot,...,8-16 ft.,15,117,109,1,1998-01-02,WAS,IND,Regular Season,1997-98
1,29700427,406,100,Tim Legler,1610612764,Washington Wizards,4,9,36,Jump Shot,...,8-16 ft.,14,143,25,0,1998-01-02,WAS,IND,Regular Season,1997-98
2,29700427,475,100,Tim Legler,1610612764,Washington Wizards,4,3,7,Jump Shot,...,8-16 ft.,10,-87,55,0,1998-01-02,WAS,IND,Regular Season,1997-98
3,29700427,487,100,Tim Legler,1610612764,Washington Wizards,4,1,45,Jump Shot,...,Less Than 8 ft.,5,-1,53,0,1998-01-02,WAS,IND,Regular Season,1997-98
4,29700427,497,100,Tim Legler,1610612764,Washington Wizards,4,0,45,Jump Shot,...,8-16 ft.,14,89,113,0,1998-01-02,WAS,IND,Regular Season,1997-98

### Loop through seasons and chunk out to individual files

In [34]:
seasons = list(season_dict.values())

In [39]:
for season in seasons:
    df_season = df[df['Season']==season]
    df_season.to_csv('NBA Shot Locations_' + season +'.csv')

In [40]:
pwd

'C:\\Users\\king2\\Documents\\Sam Docs\\Python\\Data Apps\\NBA\\Data'